### ISSUE TITLE
Generator uses a lot of memory

### ISSUE THREAD

**Issue by seasquirt** [b3spectacled/modernbetaforge#16]
I have no idea how exactly to figure out why this happens, but it seems like the modern beta generators use almost double the memory of the vanilla ones. This results in the memory usages ticking up very quickly causing frequent garbage collection which makes the game stutter every 3-ish seconds. This only happens when new chunks are generating, and if youre not generating any chunks the game runs fine. I've attached screenshots to compare the memory usage between default and the modern beta preset in my modpack and also in a fresh pack with only the modern beta mod. 

Default world gen (in modpack):
![Image](https://github.com/user-attachments/assets/a325a5f2-275e-4155-90d0-caa2d46acbd4)

Modern beta world gen(in modpack):
![Image](https://github.com/user-attachments/assets/58c254a1-f721-44f7-8d83-922f51e1da57)

Default world gen (only fermium):
![Image](https://github.com/user-attachments/assets/8e05a1bc-2a1c-404c-b90a-ca1262580286)

Modern beta world gen(only fermium):
![Image](https://github.com/user-attachments/assets/73296f5e-cd8a-4e4e-b988-0b05d593f603)

Forge: 2860
Minecraft: 1.12.2

Hardware
CPU: ryzen 9 5950x
RAM: 32GB (8GB allocated to mc)
GPU: RTX 3090
VRAM: 24GB

**Comment by b3spectacled** [comment]
The chunk generator is custom and does a lot more per-chunk vs. the vanilla one. That said, I will try to optimize it more.

**Comment by b3spectacled** [comment]
I think I've identified and optimized the main culprits for base memory consumption and memory churn. If possible, could you try the build at this link?

https://github.com/b3spectacled/modernbetaforge/actions/runs/14323665746/artifacts/2899667443

Please let me know if it improves the situation for your mod pack.

**Comment by seasquirt** [comment]
So this is a weird one. It worked the _first_ time but not after. my memory usage went down by half during the first test, however, when i closed and reopened the game it was back where it was before... I did a spark profile of the server while i had the game open the second time if you want to take a look at it (this is for the full modpack but the issue also happens on the small one) 
[https://spark.lucko.me/Q5BY0fw0uk](https://spark.lucko.me/Q5BY0fw0uk)

**Comment by Sanmaell** [comment]
I'm having the same problem

**Comment by b3spectacled** [comment]
@seasquirt, okay, please try this new build out: https://github.com/b3spectacled/modernbetaforge/actions/runs/14336351250/artifacts/2903815044

While not necessarily related to the memory issues, I did see in your Spark report that there could be lag spikes related to BuildCraft's oil generator, so I've implemented a pretty decent optimization which should help for worlds that don't attempt to add ocean/beach biomes. Please try profiling with the exact same settings and seed. Could you also share the generator settings string that is being used for this test?

I am still confused by the issue occurring on the minimal mod set. I've been profiling memory usage in my development environment and with Spark and nothing particularly weird stands out after my initial optimizations.

EDIT: Another build here, addressing another possible pain point. Overall memory usage may go up slightly from the initial optimized build, but the ultimate goal is reducing the GC load: https://github.com/b3spectacled/modernbetaforge/actions/runs/14340374151/artifacts/2905362572

**Comment by seasquirt** [comment]
Alright, so the memory usage went back down to half again on the first tests only again. These tests are using the version you sent in your edit

Here are the spark profiles over 4 tests

Full pack, First test, Memory around 20%
[https://spark.lucko.me/Udq6DbvGLw](https://spark.lucko.me/Udq6DbvGLw)

Full pack, Second test, Memory around 40%
[https://spark.lucko.me/p9RLHdSDMt](https://spark.lucko.me/p9RLHdSDMt)

Simple pack, First test, Memory around 3%
[https://spark.lucko.me/xmRflnRkJQ](https://spark.lucko.me/xmRflnRkJQ)

Simple pack, First test, Memory around 5%
[https://spark.lucko.me/3pEGRBNa32](https://spark.lucko.me/3pEGRBNa32)

Generator settings:
{"chunkSource":"modernbetaforge:beta","biomeSource":"modernbetaforge:beta","surfaceBuilder":"modernbetaforge:beta","caveCarver":"modernbetaforge:beta","worldSpawner":"modernbetaforge:beta","singleBiome":"minecraft:plains","defaultBlock":"minecraft:stone","defaultFluid":"minecraft:water","replaceOceanBiomes":false,"replaceBeachBiomes":false,"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"scaleNoiseScaleX":1.121,"scaleNoiseScaleZ":1.121,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"seaLevel":64,"height":128,"tempNoiseScale":1.0,"rainNoiseScale":1.0,"detailNoiseScale":1.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"useBiomeDepthScale":false,"biomeSize":4,"riverSize":4,"layerType":"vanilla","layerSize":4,"endIslandOffset":100.0,"endIslandWeight":8.0,"endOuterIslandOffset":100.0,"endOuterIslandDistance":64,"useEndOuterIslands":true,"caveWidth":1.0,"caveHeight":128,"caveCount":40,"caveChance":15,"useDungeons":true,"dungeonChance":8,"useStrongholds":true,"useVillages":false,"useVillageVariants":false,"useMineShafts":true,"useTemples":false,"useMonuments":false,"useMansions":false,"useRavines":false,"useUnderwaterCaves":false,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useSandstone":true,"useOldNether":true,"useNetherCaves":true,"useFortresses":false,"useLavaPockets":false,"useInfdevWalls":true,"useInfdevPyramids":true,"levelTheme":"normal","levelType":"island","levelWidth":256,"levelLength":256,"levelHeight":64,"levelHouse":"oak","useIndevCaves":true,"levelCaveWidth":1.0,"claySize":33,"clayCount":10,"clayMinHeight":0,"clayMaxHeight":128,"dirtSize":33,"dirtCount":20,"dirtMinHeight":0,"dirtMaxHeight":128,"gravelSize":33,"gravelCount":10,"gravelMinHeight":0,"gravelMaxHeight":128,"graniteSize":33,"graniteCount":0,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":0,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":0,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16,"emeraldSize":3,"emeraldCount":0,"emeraldMinHeight":95,"emeraldMaxHeight":128,"quartzSize":14,"quartzCount":0,"magmaSize":33,"magmaCount":0,"useTallGrass":true,"useNewFlowers":false,"useDoublePlants":false,"useLilyPads":false,"useMelons":false,"useDesertWells":false,"useFossils":false,"useSandDisks":false,"useGravelDisks":false,"useClayDisks":false,"useBirchTrees":true,"usePineTrees":true,"useSwampTrees":false,"useJungleTrees":false,"useAcaciaTrees":false,"spawnNewCreatureMobs":false,"spawnNewMonsterMobs":false,"spawnWaterMobs":true,"spawnAmbientMobs":false,"spawnWolves":true,"useModdedBiomes":true,"desertBiomeBase":"modernbetaforge:beta_desert","desertBiomeOcean":"modernbetaforge:beta_ocean","desertBiomeBeach":"modernbetaforge:beta_desert","forestBiomeBase":"modernbetaforge:beta_forest","forestBiomeOcean":"modernbetaforge:beta_ocean","forestBiomeBeach":"modernbetaforge:beta_beach","iceDesertBiomeBase":"modernbetaforge:beta_tundra","iceDesertBiomeOcean":"modernbetaforge:beta_frozen_ocean","iceDesertBiomeBeach":"modernbetaforge:beta_snowy_beach","plainsBiomeBase":"modernbetaforge:beta_plains","plainsBiomeOcean":"modernbetaforge:beta_ocean","plainsBiomeBeach":"modernbetaforge:beta_beach","rainforestBiomeBase":"modernbetaforge:beta_rainforest","rainforestBiomeOcean":"modernbetaforge:beta_ocean","rainforestBiomeBeach":"modernbetaforge:beta_beach","savannaBiomeBase":"modernbetaforge:beta_savanna","savannaBiomeOcean":"modernbetaforge:beta_ocean","savannaBiomeBeach":"modernbetaforge:beta_beach","shrublandBiomeBase":"modernbetaforge:beta_shrubland","shrublandBiomeOcean":"modernbetaforge:beta_ocean","shrublandBiomeBeach":"modernbetaforge:beta_beach","seasonalForestBiomeBase":"modernbetaforge:beta_seasonal_forest","seasonalForestBiomeOcean":"modernbetaforge:beta_ocean","seasonalForestBiomeBeach":"modernbetaforge:beta_beach","swamplandBiomeBase":"modernbetaforge:beta_swampland","swamplandBiomeOcean":"modernbetaforge:beta_ocean","swamplandBiomeBeach":"modernbetaforge:beta_beach","taigaBiomeBase":"modernbetaforge:beta_taiga","taigaBiomeOcean":"modernbetaforge:beta_frozen_ocean","taigaBiomeBeach":"modernbetaforge:beta_snowy_beach","tundraBiomeBase":"modernbetaforge:beta_tundra","tundraBiomeOcean":"modernbetaforge:beta_frozen_ocean","tundraBiomeBeach":"modernbetaforge:beta_snowy_beach"}

if it helps you any, im using the 1.7.9_08 beta of my modpack to test it on for the full pack tests
[https://www.curseforge.com/minecraft/modpacks/mangoplus](https://www.curseforge.com/minecraft/modpacks/mangoplus)

For the simple version for standalone tests im only using
modernbeta, fermium, fermium booter, and spark

**Comment by b3spectacled** [comment]
Thank you for your patience and for providing all of the additional data.

Here's another build (I failed to properly implement the previous fix wrt BuildCraft's oil generators, which is done properly here): https://github.com/b3spectacled/modernbetaforge/actions/runs/14365394193/artifacts/2914206432

Sorry, I'm pretty stumped on this. Based on your Spark reports and my own tests (also with Spark and etc.), it looks like a potential source of generation lag could be due to other world gen mods, in particular Millenaire? Memory consumption aside, do you also have lag issues on the minimal mod set? I have a relatively decent setup (Ryzen 7 5800x3D with 32 GB memory and 8GB allocated to MC) so that may be masking the issue somewhat; I do experience the lag issues on the full mod pack.

**Comment by seasquirt** [comment]
The minimal mod set seems to be doing pretty much fine lag spike wise, but as a side note the memory consumption is now high on the minimal pack too. On the regular pack it now reaches 60%. As for Millenaire, ive tested the pack without it and the gc problems still occur, same with project red which also causes lag sometimes.

Minimal pack memory usage at 28%
![Image](https://github.com/user-attachments/assets/e01e6db9-c1ab-4500-9b20-cdcd4a1708ad)

**Comment by b3spectacled** [comment]
Can you clarify whether this is a multiplayer server that the mods are running on, since you had mentioned running it on a server a few messages back?

And yeah, the low for memory usage being 2000 MB is not good.

**Comment by seasquirt** [comment]
This is all in singleplayer, I was clarifying the spark profile type. /sparkc measures client stuff and /spark does the integrated server, so all the profiles ive sent have been of the integrated server. Though if you want to get really specific, I have run the mod on a server before and it performs fine since the server does all of the processing and gc so the frame drops dont occur clientside.

**Comment by b3spectacled** [comment]
I've only got one more idea/question: Are you currently using custom or optimized Java VM flags?

If not, these flags may help, at the cost of higher baseline memory usage based my own tests:
```
-XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:G1ConcRSHotCardLimit=16 -XX:AllocatePrefetchStyle=3
```
From: https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks?tab=readme-ov-file#server-g1gc

This is not a solution, but right now I am just not able to reproduce the issue in my environment, using your mod pack and generator settings. Here are my last two tests using the above Java flags:

Mod pack, Modern Beta:
https://spark.lucko.me/dwbdfZpLbN

Mod pack, Vanilla:
https://spark.lucko.me/cdhRkPlIio

Without the flags, my experience has been that the memory usage goes from ~600-700 MB to ~2500-3000 MB before being garbage collected and resetting to the former, regardless of the world has been newly created, closed then reopened, etc. Memory load does not seem different vs. vanilla either.

**Comment by seasquirt** [comment]
I am not using any jvm flags anymore, I used too but they didn't help. I just tested with the ones you sent and its not a noticeable change performance wise. Hmm. I guess in the morning I'll go through all of the mods to see if anything else is causing other problems. The first new build you sent worked great for a bit but stopped working which has me the most confused. I have no clue why the second time I ran the pack the memory usage went back to double for me and never went back down... I'll do a bunch more testing when I wake up, meanwhile I did a super unorthodox probably not helpful test but who knows there may be something useful in here.

In my pack I've been working on client optimization and it got good enough that I could go to 64 render distance, thus here are the spark profiles and the heap summary with modern beta chunks constantly generating. The memory got maxed out at 95% still using 8GB allocated. May be helpful, may not, I'm not sure. I figured since chunks were generating the whole time and the memory was full we may as well see what's in it

Client Profile:
[https://spark.lucko.me/IiVBKyVfkq](https://spark.lucko.me/IiVBKyVfkq)

Server Profile:
[https://spark.lucko.me/A2zDTRsRTY](https://spark.lucko.me/A2zDTRsRTY)

Heap Summary:
[https://spark.lucko.me/WIr2O1Jy3v](https://spark.lucko.me/WIr2O1Jy3v)

**Comment by b3spectacled** [comment]
Thanks for including the heap summary. Looking at it, the total memory consumed by Modern Beta objects (filtering by `mod.bespectacled`) is just a few megabytes max. That's not the whole picture though since we need to look at world generator-related Minecraft objects (filtering by `net.minecraft`) and also the more expensive-looking Java primitive array types (filtering by `byte[]`, `char[]`, `int[]`, and `double[]`) which are used to store information during world generation.

Here's a snapshot of my development instance's heap (where my development environment is just Forge and Modern Beta. I also have Biomes O' Plenty and Dynamic Trees but they are disabled here), after I've just teleported into a completely new section of the world to generate:

![Development environment heap snapshot](https://i.imgur.com/Hkr2zM8.png)

Don't mind the significant memory consumption of BlockPos objects. Minecraft (rather inefficiently) uses these for everything from world generation, to rendering, to block ticking, and it's mostly the last two things that are eating up memory. I don't see anything unusual based on the usage breakdown.

The `byte[]` objects take up 167.5 MB in my environment while they are using 1.3 GB in your heavily modded one. From what I can tell, this type is mostly just used for Chunk IO, normal Minecraft stuff and nothing my mod interacts with.

The `char[]` objects handle text data usually but in this case 99% of the memory usage is used to store interim chunk data (`ChunkPrimer` objects) during generation, before finalization as a complete `Chunk`. This is one of the areas I targeted for optimization since I did somewhat carelessly waste memory on ChunkPrimers but it's not too bad here (131 MB in my case vs. 323.5 in yours).

`int[]` objects looks mostly used for client-side rendering. `long[]` objects looks to be mostly used for setting block data. These last two things again don't really interact with what my mod does.

The only really big discrepancy I see between my dev environment and yours is the `java.lang.object[]` objects. But that may be due to your other mods. If you didn't know, `object[]` just refers to a 'collection' of the basic Java object type (of which all other object types are related to) so I can't really tell what it's being used for.

Going back to the server profile log. Again I see that half of the CPU time is in the chunk population step (after base terrain gen, adding decorations and structures), adding other mod stuff like BuildCraft oil springs, Millenaire villages, and Project Red's volcanoes. That said, CPU time taken doesn't really speak to memory consumption (but is certainly a source of lag, as we've mentioned earlier).

One last graph and some technical explanations (thanks for reading to the end of this BTW) for why I think my mod isn't leaking memory: 

![Development environment GC snapshot](https://i.imgur.com/fZ0X1He.png)

This is my development profiler graphing GC usage. I'm not a Java whiz but my understanding is that basically the heap is divided up into three distinct sections (more information [here](https://www.oracle.com/java/technologies/visual-garbage-collection-monitoring-tool.html)):

* Eden space (memory space for new objects)
* Survivor space (memory space for objects that survive garbage collection)
* Old gen space (memory space for objects that have survived garbage collection for a long, i.e. are still being used in some way)

You can see in the Eden space two portions of random rapid spikes. This was me rapidly flying through new chunks in Spectator mode and forcing them to quickly generate, queuing up many throwaway objects. You can see under GC time (amount of time spent garbage collecting) the GC trying to keep up. The center slow rise was when I stopped for a bit to let the chunks around me generate. Then under old gen you can see objects accumulating in memory which is definitely intended! Some of this I believe is due to my mod caching world generation information for reuse later to reduce CPU/memory waste. I did tweak cache sizes in one of the above builds to reduce memory footprint. Finally the flatlines at the end is me quitting and idling on the main menu. At some point the GC does clean up the Old gen space and returns to a typical level.

All this to say, the GC looks to be functioning as it should and cleaning up memory. The graphs look about the same in vanilla worlds as well.

Again, thanks for bearing with me. I haven't really attempted to optimize the mod to this degree before so this was an illuminating experience LOL.

EDIT: One additional note, it does look like memory usage does generally accumulate over time in the old gen space without being garbage collected while still in a world, even in vanilla. In this way, it's possible for there to be memory leaks despite it being Java. Perhaps another mod is maintaining object references that aren't flushed out when exiting back to the main menu. I will certainly take a look at my mod to make sure I haven't fallen for the common pitfalls.

**Comment by b3spectacled** [comment]
I've just incorporated all of these adjustments into release 1.12.2-1.6.1.1.

I will keep this issue open so people can continue to report memory issues.
